AlexaNewProject/Models/SearchModel.cs
using Sitecore.Data.Items;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AlexaNewProject.Models
{   
    public class SearchModel
    {
        public string ItemName { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public byte[] ArticleSmallImage { get; set; }
        public byte[] ArticleLargeImage { get; set; }
        public string Category { get; set; }
        public string PostedDate { get; set; }
        public string Readonbtn { get; set; }
        public Sitecore.Data.Items.Item sitecoreItem { get; set; }
        public string BlogURL { get; set; }
        public string BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string BlogSImage { get; set; }
        public string PostCardButtonText { get; set; }
    }
}

AlexaNewProject/Controllers/AlexaNewProjectIndexController.cs
using AlexaNewProject.Models;
using Sitecore;
using Sitecore.Data.Items;
using Sitecore.Resources.Media;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlexaNewProject.Controllers
{
    public class AlexaNewProjectIndexController : Controller
    {
        // GET: AlexaNewProjectIndex
        public ActionResult Index()
        {
            return View();
        }
       
        //public ActionResult DoSearch(string searchText)
        //{
        //    var myResults = new SearchResults
        //    {
        //        Results = new List<SearchResult>()
        //    };
        //    var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
        //    var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
        //    using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
        //    {
        //        //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
        //        //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
        //        var searchResults = searchContext.GetQueryable<SearchModel>()
        //            .Where(x => x.Title.Contains(searchText) || x.ShortDescription.Contains(searchText));   //LINQ query
        //        var fullResults = searchResults.GetResults();

        //        // This is better and will get paged results - page 1 with 10 results per page
        //        //var pagedResults = searchResults.Page(1, 10).GetResults();
        //        foreach (var hit in fullResults.Hits)
        //        {
        //            myResults.Results.Add(new SearchResult
        //            {
        //                Category = hit.Document.Category,
        //                Title = hit.Document.Title,
        //                ShortDescription = hit.Document.ShortDescription,
        //                LongDescription = hit.Document.LongDescription,
        //                PostedDate = hit.Document.PostedDate,
        //                ArticleSmallImage = hit.Document.ArticleSmallImage
        //            });
        //        }
        //        return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = myResults };
        //    }
        //}

        ///// <summary>
        ///// Search logic
        ///// </summary>
        ///// <param name="searchText">Search term</param>
        ///// <returns>Search predicate object</returns>
        //public static Expression<Func<SearchModel, bool>> GetSearchPredicate(string searchText)
        //{
        //    var predicate = PredicateBuilder.True<SearchModel>(); // Items which meet the predicate
        //                                                          // Search the whole phrase - LIKE
        //                                                          // predicate = predicate.Or(x => x.DispalyName.Like(searchText)).Boost(1.2f);
        //                                                          // predicate = predicate.Or(x => x.Description.Like(searchText)).Boost(1.2f);
        //                                                          // predicate = predicate.Or(x => x.Title.Like(searchText)).Boost(1.2f);
        //                                                          // Search the whole phrase - CONTAINS
        //    predicate = predicate.Or(x => x.LongDescription.Contains(searchText)); // .Boost(2.0f);
        //    predicate = predicate.Or(x => x.ShortDescription.Contains(searchText)); // .Boost(2.0f);
        //    predicate = predicate.Or(x => x.Title.Contains(searchText)); // .Boost(2.0f);
        //    //Where Author="searchText" OR Description="searchText" OR Title="searchText"
        //    return predicate;
        //}
       
       
        public ActionResult searchPredicate(FormCollection form)
        {
            string query = form["searchInput"];
            List<Sitecore.Data.Items.Item> blogItems = new List<Sitecore.Data.Items.Item>();
            List<SearchModel> BlogCardsCollection = new List<SearchModel>();
            var rootitem = Sitecore.Context.Database.GetItem("{BD633124-74A8-4509-AC5F-156216F4BEB5}");
            var Websitesettings = Sitecore.Context.Database.GetItem("{C50D9B83-B0E3-4506-AE33-FF110A97595E}");

            blogItems = rootitem.Axes.GetDescendants().ToList();

            foreach (Sitecore.Data.Items.Item items in blogItems.ToList())
            {
                if (items.TemplateID.ToString() != "{CD905BD2-E758-46B6-98EB-6B139A4162AE}")
                {
                    blogItems.Remove(items);
                }
            }

            for (int i = 0; i < blogItems.Count; i++)
            {
                SearchModel BlogModel = new SearchModel();
                var imageUrl = string.Empty;

                Sitecore.Data.Fields.ImageField imageField = blogItems[i].Fields["ArticleSmallImage"];
                if (imageField?.MediaItem != null)
                {
                    var image = new MediaItem(imageField.MediaItem);
                    imageUrl = StringUtil.EnsurePrefix('/', MediaManager.GetMediaUrl(image));
                    BlogModel.BlogSImage = imageUrl;
                }
                BlogModel.Category = blogItems[i].Fields["Title"].Value;
                BlogModel.Title = blogItems[i].Fields["ShortDescription"].Value;

                Sitecore.Data.Fields.DateField dateTimeField = blogItems[i].Fields["PostedDate"];

                string dateTimeString = dateTimeField.Value;

                DateTime dateTimeStruct = Sitecore.DateUtil.IsoDateToDateTime(dateTimeString);
                BlogModel.PostedDate = dateTimeStruct.ToShortDateString();

                BlogModel.ShortDescription = blogItems[i].Fields["ShortDescription"].Value;
                BlogModel.LongDescription = blogItems[i].Fields["LongDescription"].Value;
                BlogModel.PostCardButtonText = Websitesettings.Fields["PostCardButtonText"].Value;
                BlogModel.sitecoreItem = blogItems[i];
                BlogModel.BlogURL = Sitecore.Links.LinkManager.GetItemUrl(blogItems[i]);


                BlogCardsCollection.Add(BlogModel);
            }

            if (query is null)
                query = "hi";

            List<SearchModel> results = BlogCardsCollection.FindAll(Findtitle);



            bool Findtitle(SearchModel bk)
            {

                if (bk.Title.Contains(query) || bk.Category.Contains(query) || bk.ShortDescription.Contains(query) || bk.LongDescription.Contains(query))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }

            ViewBag.searchCards = results;
            return View("~/Views/Soumya/SearchCards.cshtml", ViewBag.searchCards);
        }

    }
}

AlexaNewProject/Views/Soumya/ArticleBody.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<body>
    <div>
        <h4>@Html.Sitecore().Field("BlogId", new { DisableWebEdit = true })</h4>
        <h4>@Html.Sitecore().Field("posteddate", new { format = "yyyy-MMM-dd" })</h4>
        <h4>@Html.Sitecore().Field("ArticleLargeImage", new { w = 1110, h = 751 })</h4>
        <h4>@Html.Sitecore().Field("LongDescription")</h4>
    </div>

</body>
<script src="~/assets/js/jquery-3.3.1.slim.min.js"></script>
<script src="~/assets/js/bootstrap.bundle.js"></script>
<link href="~/assets/css/blogsite.css" rel="stylesheet" />

AlexaNewProject/Views/Soumya/BlogDetails.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">

<main role="main" class="container blog-post-detail">
    <div class="row">
        <div class="blog-post-detail-card card col-lg-12">
            @*<img class="card-img-top" src="@Html.Sitecore().Field("ArticleLargeImage")" alt="Card image cap">*@
            @Html.Sitecore().Field("ArticleLargeImage", new { w = 1110, h = 751 })
            <div class="card-body bg-light">
                <strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("CategoryName")</strong>
                <h3 class="card-title">@Html.Sitecore().Field("ShortDescription")</h3>
                <div class="mb-1 text-muted">@Html.Sitecore().Field("PostedDate", new { format = "MMM-dd-yyyy" })</div>
                <p>
                    @Html.Sitecore().Field("LongDescription")
                </p>
                <div class="blog-detail-tag-list">
                    <span class="read-more-heading">Read more: </span>
                    <a class="btn btn-info" href="#" role="button">Tag</a>
                    <a class="btn btn-info" href="#" role="button">Super Extra Long Tag</a>
                    <a class="btn btn-info" href="#" role="button">Extra Long Tag</a>
                </div>
            </div>
        </div>
    </div>
</main>

AlexaNewProject/Views/Soumya/BlogList.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">

<main role="main" class="container blog-posts">
    <div class="row" id="postIdBlog">
        <!-- Begin Repeating Elements Area -->
        <!-- Begin Repeating Element-->

        @{
            //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Soumya/Home/Articles/AAA");
            var item = Sitecore.Context.Database.GetItem("{ABCBDFDA-DA64-4413-A1B6-78AD995A3039}");
        }

        <div class="blog-post-card card col-lg-4 col-md-6">
            <img class="card-img-top" alt="Card image cap" @Html.Sitecore().Field("ArticleSmallImage", item, new { width = "350", height = "410" })
            <div class="card-body bg-light"><strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("Title", item)</strong>
                <h3 class="card-title">@Html.Sitecore().Field("ShortDescription", item)</h3>
                <div class="mb-1 text-muted"> @Html.Sitecore().Field("PostedDate", item, new { format = "MMM-yyyy-dd" }) </div>
                <p>@Html.Sitecore().Field("LongDescription", item)</p>
                <a href="#" class="btn btn-warning btn-block">Read on</a>
            </div>
        </div>
        <!-- End Repeating Element-->
        <!-- Begin Repeating Element-->
        @{
            //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Soumya/Home/Articles/AAA");
            var item2 = Sitecore.Context.Database.GetItem("{C35603B2-5E0B-49AD-AB68-CF383C38E98C}");
        }
    <div class="blog-post-card card col-lg-4 col-md-6">
        <img class="card-img-top" alt="Card image cap" @Html.Sitecore().Field("ArticleSmallImage", item2,new { width = "350", height = "410" }) 
        <div class="card-body bg-light">
            <strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("Title", item2)</strong>
            <h3 class="card-title">@Html.Sitecore().Field("ShortDescription", item2)</h3>
            <div class="mb-1 text-muted"> @Html.Sitecore().Field("PostedDate", item2, new { format = "MMM-yyyy-dd" }) </div>
            <p> @Html.Sitecore().Field("LongDescription", item2)</p>
            <a href="#" class="btn btn-warning btn-block">Read on</a>
        </div>
    </div>
        <!-- End Repeating Element-->
        <!-- Begin Repeating Element-->
        @{
            //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Soumya/Home/Articles/AAA");
            var item3 = Sitecore.Context.Database.GetItem("{95FF8262-C020-4F39-9220-B8BF3292BD95}");
        }
    <div class="blog-post-card card col-lg-4 col-md-6">
        <img class="card-img-top" alt="Card image cap" @Html.Sitecore().Field("ArticleSmallImage", item3,new { width = "350", height = "410" }) 
        <div class="card-body bg-light"><strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("Title", item3)</strong>
            <h3 class="card-title">@Html.Sitecore().Field("ShortDescription", item3)</h3>
            <div class="mb-1 text-muted"> @Html.Sitecore().Field("PostedDate", item3, new { format = "MMM-yyyy-dd" }) </div>
            <p> @Html.Sitecore().Field("LongDescription", item3)</p>
            <a href="#" class="btn btn-warning btn-block">Read on</a>
        </div>
    </div>
        <!-- End Repeating Element-->
        <!-- Begin Repeating Element-->
        @{
            //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Soumya/Home/Articles/AAA");
            var item4 = Sitecore.Context.Database.GetItem("{9C9DB880-2F3E-4473-A010-B9CF5FC97E86}");
        }
    <div class="blog-post-card card col-lg-4 col-md-6">
        <img class="card-img-top" alt="Card image cap" @Html.Sitecore().Field("ArticleSmallImage", item4,new { width = "350", height = "410" }) 
        <div class="card-body bg-light"><strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("Title", item4)</strong>
            <h3 class="card-title">@Html.Sitecore().Field("ShortDescription", item4)</h3>
            <div class="mb-1 text-muted"> @Html.Sitecore().Field("PostedDate", item4, new { format = "MMM-yyyy-dd" }) </div>
            <p> @Html.Sitecore().Field("LongDescription", item4)</p>
            <a href="#" class="btn btn-warning btn-block">Read on</a>
        </div>
    </div>
        <!-- End Repeating Element-->
        <!-- Begin Repeating Element-->
        @{
            //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Soumya/Home/Articles/AAA");
            var item5 = Sitecore.Context.Database.GetItem("{D6E88F93-0DE9-4FD6-8078-FDF489AC870B}");
        }
    <div class="blog-post-card card col-lg-4 col-md-6">
        <img class="card-img-top" alt="Card image cap" @Html.Sitecore().Field("ArticleSmallImage", item5,new { width = "350", height = "410" })
        <div class="card-body bg-light"><strong class="d-inline-block mb-2 text-success">@Html.Sitecore().Field("Title", item5)</strong>
            <h3 class="card-title"> @Html.Sitecore().Field("ShortDescription", item5)</h3>
            <div class="mb-1 text-muted"> @Html.Sitecore().Field("PostedDate", item5, new { format = "MMM-yyyy-dd" }) </div>
            <p> @Html.Sitecore().Field("LongDescription", item5)</p>
            <a href="#" class="btn btn-warning btn-block">Read on</a>
        </div>
    </div>
        <!-- End Repeating Element-->
        <!-- End Repeating Elements Area -->
    </div>
</main>
@*<div id="resultsItem"></div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
$(document).ready(function () {
    $("#btnSearch").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "AlexaNewProjectIndex")",
                    contentType: "application/json",
                    data: {
                        searchText: $("#SearchInput").val()
                    },
                    success: function (result) {
                    var resultText = "";
                    $('#resultsItem').text(resultText);
                    $('#resultsItem').append("Results from  Site <BR><BR>");
                    $(result.Results).each(function (index, item) {
                    // each iteration
                    var Title = item.Title;
                    var Image = item.ArticleSmallImage;
                    var ShortDescription = item.ShortDescription;
                    var LongDescription = item.LongDescription;
                    var PostedDate = item.PostedDate;
                    //resultText += (index + 1) + " - " + Description + Title + "; " + MobileBrand + Title + "; " + Category + "; " + "<BR><BR>";
                        resultText += '<main role="main" class="container blog-posts">' + '<div>'

</script>*@

AlexaNewProject/Views/Soumya/DefaultLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<head lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
    <link rel="stylesheet" href="~/assets/css/blogsite.css">
    </head>
    <body>
        <div>
            @Html.Sitecore().Placeholder("PhMain")
        </div>
    </body>

AlexaNewProject/Views/Soumya/Footer.cshtml
@{
    var item = Sitecore.Context.Database.GetItem("{AE392C5D-9844-4E08-9DAC-54A4E281910C}");
}

<Footer>
    <div class="container">
        <div class="text-white bg-primary">
            <p class="lead">@Html.Sitecore().Field("Copyright", item)</p>
        </div>
    </div>
</Footer>	

AlexaNewProject/Views/Soumya/Header.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
    <title>Sitecore Powered Mobile Website</title>
</head>

<body>
    <header>
        <div class="container">
            <div class="jumbotron text-white bg-primary">
                <h1 class="display-3">
                    @{
                        var item = Sitecore.Context.Database.GetItem("{AE392C5D-9844-4E08-9DAC-54A4E281910C}");
                    }
                    <div>
                        @Html.Sitecore().Field("Header-Title", item)
                    </div>
                </h1>
                <p class="lead"><a href="https://jss.sitecore.com/" class="text-light">Sitecore</a>  @Html.Sitecore().Field("Header-SubTitle", item)</p>
            </div>
        </div><!-- /.container -->
    </header>
</body>
</html>

AlexaNewProject/Views/Soumya/Search.cshtml
@{
    ViewBag.Title = "SOLR Search Component";
    var item = Sitecore.Context.Database.GetItem("{C50D9B83-B0E3-4506-AE33-FF110A97595E}");
}
@using (Html.BeginRouteForm(Sitecore.Mvc.Configuration.MvcSettings.SitecoreRouteName, FormMethod.Post))
{
    @Html.Sitecore().FormHandler("AlexaNewProjectIndex", "searchPredicate")

    <div class="main-search">
        <div class="input-group">
            @Html.TextBox("searchInput", "", new { @class = "form-control", placeholder = @Html.Sitecore().Field("HighlighterText", item), autocomplete = "off" })
            <div class="input-group-append">
                <input type="submit" id="btnSearch" class="btn btn-dark" value=@Html.Sitecore().Field("ButtonLabel", item) />
            </div>
        </div>
    </div>
}

AlexaNewProject/Views/Soumya/SearchCards.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@using AlexaNewProject.Models
@{
    Layout = null;
    var item = Sitecore.Context.Database.GetItem("{7F31B620-066C-4498-A7F9-99315C4F1DC6}");
}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
    <title>Sitecore Powered Mobile Website</title>
</head>

    <header>
        <div class="container">
            <div class="jumbotron text-white bg-primary">
                <h1 class="display-3">
                    @{
                        var item1 = Sitecore.Context.Database.GetItem("{C50D9B83-B0E3-4506-AE33-FF110A97595E}");
                    }
                    <div>
                        @Html.Sitecore().Field("Header-Title", item1)
                    </div>
                </h1>
                <p class="lead"><a href="https://jss.sitecore.com/" class="text-light">Sitecore</a>@Html.Sitecore().Field("Header-SubTitle", item1)</p>
            </div>
        </div><!-- /.container -->
    </header>
@using (Html.BeginRouteForm(Sitecore.Mvc.Configuration.MvcSettings.SitecoreRouteName, FormMethod.Post))
{
    @Html.Sitecore().FormHandler("AlexaNewProjectIndex", "searchPredicate")
    <div class="main-search">
        <div class="input-group">
            @Html.TextBox("searchInput", "", new { @class = "form-control", placeholder = @Html.Sitecore().Field("HighlighterText", item1), autocomplete = "off" })
            <div class="input-group-append">
                <input type="submit" id="btnSearch" class="btn btn-dark" value=@Html.Sitecore().Field("ButtonLabel", item1) />
            </div>
        </div>
    </div>
    <br>
}
<body>
    @if (ViewBag.searchCards != null)
    {
        <main role="main" class="container blog-posts">
            <div class="row">
                @foreach (SearchModel Postcards in (List<SearchModel>)ViewBag.searchCards)
                {
                    <div class="blog-post-card card col-lg-4 col-md-6">
                        @Html.Sitecore().Field("ArticleSmallImage", Postcards.sitecoreItem, new { width = "350", height = "410" })
                        <div class="card-body bg-light">
                            <strong class="d-inline-block mb-2 text-success">Design</strong>
                            <h3 class="card-title">@Postcards.ShortDescription</h3>
                            <div class="mb-1 text-muted">@Postcards.PostedDate</div>
                            <p>@Postcards.LongDescription</p>
                            <a href="@Postcards.BlogURL" class="btn btn-warning btn-block">Read on</a>
                        </div>
                    </div>
                }
            </div>
        </main>
    }

</body>
<Footer>
    <div class="container">
        <div class="text-white bg-primary">
            <p class="lead"> @Html.Sitecore().Field("Copyright", item1)</p>
        </div>
    </div>
</Footer>
</html>